# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[bun]
format = "via [$symbol]($style)"

[buf]
format = "via [$symbol]($style)"

[cmake]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"

[deno]
format = "via [$symbol]($style)"

[elixir]
format = 'via [$symbol]($style)'

[golang]
format = 'via [$symbol]($style)'

[lua]
format = 'via [$symbol]($style)'

[nodejs]
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'

[solidity]
format = 'via [$symbol]($style)'

[aws]
disabled = true
